export const ADD_NEW_POST = 'ADD_NEW_POST';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';

export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS';
export const GET_POST_DETAILS_FAIL = 'GET_POST_DETAILS_FAIL';

export const DELETE_POST_BY_ID = 'DELETE_POST_BY_ID';
export const DELETE_POST_BY_ID_SUCCESS = 'DELETE_POST_BY_ID_SUCCESS';
export const DELETE_POST_BY_ID_FAIL = 'DELETE_POST_BY_ID_FAIL';

export const UPDATE_POST_BY_ID = 'UPDATE_POST_BY_ID';
export const UPDATE_POST_BY_ID_SUCCESS = 'UPDATE_POST_BY_ID_SUCCESS';
export const UPDATE_POST_BY_ID_FAIL = 'UPDATE_POST_BY_ID_FAIL';
